# Generated by Django 4.2.7 on 2026-05-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_employee_bank_code_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clock_method',
            field=models.CharField(blank=True, choices=[('selfie', 'Selfie'), ('boxmark', 'Boxmark')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewed', 'Renewed')], default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='is_password_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('sacked', 'Sacked'), ('resigned', 'Resigned')], default='pending', max_length=15),
        ),
    ]
